In [187]:
import pandas as pd
data_lp=pd.read_csv("Loan_Default.csv")
data_lp

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,EXP,758,CIB,25-34,to_inst,98.728814,south,direct,1,45.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,EQUI,552,EXP,55-64,to_inst,NaN,North,direct,1,NaN
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,EXP,834,CIB,35-44,to_inst,80.019685,south,direct,0,46.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,EXP,587,CIB,45-54,not_inst,69.376900,North,direct,0,42.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,CRIF,602,EXP,25-34,not_inst,91.886544,North,direct,0,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148665,173555,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,...,CIB,659,EXP,55-64,to_inst,71.792763,south,direct,0,48.0
148666,173556,2019,cf,Male,nopre,type1,p1,l1,nopc,nob/c,...,CIB,569,CIB,25-34,not_inst,74.428934,south,direct,0,15.0
148667,173557,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,CIB,702,EXP,45-54,not_inst,61.332418,North,direct,0,49.0
148668,173558,2019,cf,Female,nopre,type1,p4,l1,nopc,nob/c,...,EXP,737,EXP,55-64,to_inst,70.683453,North,direct,0,29.0
148669,173559,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,...,CIB,830,CIB,45-54,not_inst,72.849462,North,direct,0,44.0

In [189]:
import warnings
warnings.filterwarnings('ignore')
import urllib.request
import io
data_lp.head(5)

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,EXP,758,CIB,25-34,to_inst,98.728814,south,direct,1,45.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,EQUI,552,EXP,55-64,to_inst,NaN,North,direct,1,NaN
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,EXP,834,CIB,35-44,to_inst,80.019685,south,direct,0,46.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,EXP,587,CIB,45-54,not_inst,69.376900,North,direct,0,42.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,CRIF,602,EXP,25-34,not_inst,91.886544,North,direct,0,39.0

In [191]:
data_lp.isnull().sum()

ID                               0
year                             0
loan_limit                    3344
Gender                           0
approv_in_adv                  908
loan_type                        0
loan_purpose                   134
Credit_Worthiness                0
open_credit                      0
business_or_commercial           0
loan_amount                      0
rate_of_interest             36439
Interest_rate_spread         36639
Upfront_charges              39642
term                            41
Neg_ammortization              121
interest_only                    0
lump_sum_payment                 0
property_value               15098
construction_type                0
occupancy_type                   0
Secured_by                       0
total_units                      0
income                        9150
credit_type                      0
Credit_Score                     0
co-applicant_credit_type         0
age                            200
submission_of_application      200
LTV                          15098
Region                           0
Security_Type                    0
Status                           0
dtir1                        24121
dtype: int64

In [193]:
data_lp = data_lp.dropna(axis=1,how='all')
data_lp.head()

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,EXP,758,CIB,25-34,to_inst,98.728814,south,direct,1,45.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,EQUI,552,EXP,55-64,to_inst,NaN,North,direct,1,NaN
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,EXP,834,CIB,35-44,to_inst,80.019685,south,direct,0,46.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,EXP,587,CIB,45-54,not_inst,69.376900,North,direct,0,42.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,CRIF,602,EXP,25-34,not_inst,91.886544,North,direct,0,39.0

In [195]:
data_lp.shape

(148670, 34)

In [197]:
data_lp.info

<bound method DataFrame.info of             ID  year loan_limit             Gender approv_in_adv loan_type  \
0        24890  2019         cf  Sex Not Available         nopre     type1
1        24891  2019         cf               Male         nopre     type2
2        24892  2019         cf               Male           pre     type1
3        24893  2019         cf               Male         nopre     type1
4        24894  2019         cf              Joint           pre     type1
...        ...   ...        ...                ...           ...       ...
148665  173555  2019         cf  Sex Not Available         nopre     type1
148666  173556  2019         cf               Male         nopre     type1
148667  173557  2019         cf               Male         nopre     type1
148668  173558  2019         cf             Female         nopre     type1
148669  173559  2019         cf             Female         nopre     type1

       loan_purpose Credit_Worthiness open_credit business_or_commercial  ...  \
0                p1                l1        nopc                  nob/c  ...
1                p1                l1        nopc                    b/c  ...
2                p1                l1        nopc                  nob/c  ...
3                p4                l1        nopc                  nob/c  ...
4                p1                l1        nopc                  nob/c  ...
...             ...               ...         ...                    ...  ...
148665           p3                l1        nopc                  nob/c  ...
148666           p1                l1        nopc                  nob/c  ...
148667           p4                l1        nopc                  nob/c  ...
148668           p4                l1        nopc                  nob/c  ...
148669           p3                l1        nopc                  nob/c  ...

        credit_type  Credit_Score  co-applicant_credit_type    age  \
0               EXP           758                       CIB  25-34
1              EQUI           552                       EXP  55-64
2               EXP           834                       CIB  35-44
3               EXP           587                       CIB  45-54
4              CRIF           602                       EXP  25-34
...             ...           ...                       ...    ...
148665          CIB           659                       EXP  55-64
148666          CIB           569                       CIB  25-34
148667          CIB           702                       EXP  45-54
148668          EXP           737                       EXP  55-64
148669          CIB           830                       CIB  45-54

        submission_of_application        LTV Region Security_Type  Status  \
0                         to_inst  98.728814  south        direct       1
1                         to_inst        NaN  North        direct       1
2                         to_inst  80.019685  south        direct       0
3                        not_inst  69.376900  North        direct       0
4                        not_inst  91.886544  North        direct       0
...                           ...        ...    ...           ...     ...
148665                    to_inst  71.792763  south        direct       0
148666                   not_inst  74.428934  south        direct       0
148667                   not_inst  61.332418  North        direct       0
148668                    to_inst  70.683453  North        direct       0
148669                   not_inst  72.849462  North        direct       0

       dtir1
0       45.0
1        NaN
2       46.0
3       42.0
4       39.0
...      ...
148665  48.0
148666  15.0
148667  49.0
148668  29.0
148669  44.0

[148670 rows x 34 columns]>

In [199]:
data_lp.dropna(inplace=True)

In [201]:
data_lp.isnull().sum()

ID                           0
year                         0
loan_limit                   0
Gender                       0
approv_in_adv                0
loan_type                    0
loan_purpose                 0
Credit_Worthiness            0
open_credit                  0
business_or_commercial       0
loan_amount                  0
rate_of_interest             0
Interest_rate_spread         0
Upfront_charges              0
term                         0
Neg_ammortization            0
interest_only                0
lump_sum_payment             0
property_value               0
construction_type            0
occupancy_type               0
Secured_by                   0
total_units                  0
income                       0
credit_type                  0
Credit_Score                 0
co-applicant_credit_type     0
age                          0
submission_of_application    0
LTV                          0
Region                       0
Security_Type                0
Status                       0
dtir1                        0
dtype: int64

In [203]:
data_lp.shape

(98187, 34)

In [205]:
import seaborn as sns
import matplotlib.pyplot as plt

In [207]:
lr_data = data_lp.copy()

In [209]:
from sklearn.linear_model import LogisticRegression

In [211]:
lr  = LogisticRegression()

In [213]:
from sklearn.preprocessing import LabelEncoder

In [215]:
le = LabelEncoder()

In [217]:
columns = lr_data.select_dtypes(include='object').columns

In [329]:
columns

Index(['loan_limit', 'Gender', 'approv_in_adv', 'loan_type', 'loan_purpose',
       'Credit_Worthiness', 'open_credit', 'business_or_commercial',
       'Neg_ammortization', 'interest_only', 'lump_sum_payment',
       'construction_type', 'occupancy_type', 'Secured_by', 'total_units',
       'credit_type', 'co-applicant_credit_type', 'age',
       'submission_of_application', 'Region', 'Security_Type'],
      dtype='object')

In [221]:
for i in columns:
    lr_data[i] = le.fit_transform(lr_data[i])

In [327]:
lr_data.head()

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
2,24892,2019,0,2,1,0,0,0,0,1,...,3,834,0,1,1,80.019685,3,0,0,46.0
4,24894,2019,0,1,1,0,0,0,0,1,...,1,602,1,0,0,91.886544,0,0,0,39.0
5,24895,2019,0,1,1,0,0,0,0,1,...,3,864,1,1,0,70.089286,0,0,0,40.0
6,24896,2019,0,1,1,0,2,0,0,1,...,3,860,1,3,1,79.109589,0,0,0,44.0
8,24898,2019,0,1,0,0,2,0,0,1,...,0,580,1,3,1,78.765690,2,0,0,44.0

In [303]:
for i in range(lr_data['Credit_Worthiness'].max()):
    print(f'{i} => {le.inverse_transform([i])}')

0 => [0]

In [305]:
X = lr_data.drop(columns=['Credit_Worthiness'])

In [307]:
Y = lr_data['Credit_Worthiness']

In [309]:
from sklearn.model_selection import train_test_split

In [311]:
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,test_size=0.3,random_state=42)

In [313]:
from sklearn.preprocessing import StandardScaler as ss

In [315]:
ss = StandardScaler()
xtrain_ss = ss.fit_transform(xtrain)
xtest_ss = ss.transform(xtest)

In [317]:
import warnings
warnings.filterwarnings('ignore')

In [319]:

lr.fit(xtrain_ss,ytrain)

LogisticRegression()

In [321]:
ypred_lr = lr.predict(xtest_ss)

In [323]:
from sklearn.metrics import accuracy_score, roc_auc_score,f1_score, confusion_matrix

In [325]:
acc_lr = accuracy_score(ytest,ypred_lr)

In [295]:
acc_lr

0.9625895372916454